# Global Configuration
[globalConfig]
# Website Title
title = "Minecraft Server - Whitelist Self-Verification"
# Contact Prompt
contactContent = "Join Discord Group"
# Group Number
contactNumber = "123456789"
# Link
contactLink = "https://discord.com/"

# Web Service Configuration
[webService]
# Host
host = "0.0.0.0"
# Port
port = 80
# Website session timeout (unit: minutes)
sessionTimeout = 10

# Email Service Configuration
[emailService]
# Host
host = "smtp.gmail.com"
# Port
port = 587
# User
username = ""
# Password
password = ""
# Verification code expiration time (unit: minutes)
verifyCodeExpireTime = 5

# Rcon Service Configuration
[rconService]
# Host
host = "127.0.0.1"
# Port
port = 25575
# Password
password = ""
